# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PERL=5.22.0.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jPJ1YCAFY6AJ1M51jXu099/VBbs+62uvSfCknGO0Gxv4Y2+EdUV5dXT8lhSFJ6C3eevPxNtbbM40jiYPSQH7IO33QZ/cKSTyHefTdM/kYWkbVPm9V28Quylo3f9xzXN0Hq4SPnM5HhHCkqadD2hZ1FlYewqfKED0pEq2qjPpecYNCpcLJU7Nh8WD8zkD36k5+LYwEcDutOGyrs8v1NDFK7+3Y9eOg+sosF8LbIl7sVawWKvlZwVuAuxr9gv+kwLx0RupM6KkQOcOE721lV5cBxjnLKpGKbwczhZAh8PwIJ0xrJX1gEIsdqv8y2KEty73pnF7xFECSND3LXkCanIMZzFNygATpJPxmMaksOgI682EWrFJ6JNwBGRR4gU8vhIq+ybypkQwm8omJz7qlE48yoGMyTTr58L5xCKt7GiBLCZ8RZdN6tOuQY0B7gJs6X4ULSumG0d+56drv37SHNgxvHo+PaOW9cJHAGg5OC4g/+uWOc70o6b+BQOt9SvadijsWYN+Nhir01TE32raZlGJkJxT4vqkDSFEYMk/WAI+P+bf6qZZsV15SknAtNfqZYX6DPF5M9D2Gk1U6Y16jMUSfJBMi+KPMoKTS8lEDT3Y1B6IenfrRujPuZDAEr3IpbkorBQs64YCfJqrS4YkdNd7itbRZDAENiHkLAHNHm7pr8w="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
