travis:
  secure:
    BINSTAR_TOKEN: jPJ1YCAFY6AJ1M51jXu099/VBbs+62uvSfCknGO0Gxv4Y2+EdUV5dXT8lhSFJ6C3eevPxNtbbM40jiYPSQH7IO33QZ/cKSTyHefTdM/kYWkbVPm9V28Quylo3f9xzXN0Hq4SPnM5HhHCkqadD2hZ1FlYewqfKED0pEq2qjPpecYNCpcLJU7Nh8WD8zkD36k5+LYwEcDutOGyrs8v1NDFK7+3Y9eOg+sosF8LbIl7sVawWKvlZwVuAuxr9gv+kwLx0RupM6KkQOcOE721lV5cBxjnLKpGKbwczhZAh8PwIJ0xrJX1gEIsdqv8y2KEty73pnF7xFECSND3LXkCanIMZzFNygATpJPxmMaksOgI682EWrFJ6JNwBGRR4gU8vhIq+ybypkQwm8omJz7qlE48yoGMyTTr58L5xCKt7GiBLCZ8RZdN6tOuQY0B7gJs6X4ULSumG0d+56drv37SHNgxvHo+PaOW9cJHAGg5OC4g/+uWOc70o6b+BQOt9SvadijsWYN+Nhir01TE32raZlGJkJxT4vqkDSFEYMk/WAI+P+bf6qZZsV15SknAtNfqZYX6DPF5M9D2Gk1U6Y16jMUSfJBMi+KPMoKTS8lEDT3Y1B6IenfrRujPuZDAEr3IpbkorBQs64YCfJqrS4YkdNd7itbRZDAENiHkLAHNHm7pr8w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
